version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: dr-classifier-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - model_data:/app/data/models
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
    networks:
      - dr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Web Application
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: dr-classifier-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dr-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  model_data:
    driver: local

networks:
  dr-network:
    driver: bridge
